export {default as MainHeader} from '$lib/comp/MainComp/header.svelte'
export { default as MainNavigation} from '$lib/comp/MainComp/navigation.svelte'
export { default as About} from '$lib/comp/MainComp/about.svelte'
export { default as Projects} from '$lib/comp/MainComp/projects.svelte' 
export { default as Experience} from '$lib/comp/MainComp/experience.svelte'
export { default as Steck} from '$lib/comp/MainComp/Stecktechnologies.svelte'
export { default as Purposes} from '$lib/comp/MainComp/purposes.svelte'
export {default as Services} from '$lib/comp/MainComp/services.svelte'
export { default as Footer} from '$lib/comp/MainComp/footer.svelte'
export { default as ScrollToTop} from '$lib/comp/MainComp/ScrollToTop.svelte'

export {default as BgAuth} from '$lib/comp/AuthComp/bg.svelte'
export {default as SignInForm} from '$lib/comp/AuthComp/signInForm.svelte'

export {default as AdminHeader} from '$lib/comp/AdminComp/AdminHeader.svelte'
export {default as AdminSidebar} from '$lib/comp/AdminComp/AdminSidebar.svelte'
export {default as ContentEditor} from '$lib/comp/AdminComp/ContentEditor.svelte'
export {default as ComponentsManager} from '$lib/comp/AdminComp/ComponentsManager.svelte'
export {default as StyleEditor} from '$lib/comp/AdminComp/ContentEditor.svelte'
export {default as SettingsEditor} from '$lib/comp/AdminComp/SettingsEditor.svelte'